language: node_js
cache: yarn
node_js:
  - "8"
  - "10"

script: yarn test

jobs:
  include:
    - stage: npm
      node_js: "8"
      if: tag =~ ^v\d.*
      deploy:
          provider: npm
          script: yarn build
          email: "jondotan@gmail.com"
          skip_cleanup: true
          api_key:
            secure: "ocZDzuf/1AzLGH8Z2TPpHBECMsHgG90NIywas/JxCiESCYq2f4xQFxUAXCvDM4r1hRYLUIZLX1KLnRXOi3Q/r/NCydGViNvfhaAb/3qkzGpHy5hPivXOC+c4jtZd0dAEgYOT3ymamyAj5gsvzJYEkgY/b+OHUU8Ui+nQ3xILQtStdTmJHczE89Kg1+bcv/KfeqhC/USEYOoNij2xDBKuOTbTBLBaMp9MuhH3lfHn07JU022EfH5qOPxKBR/VtMP0vBIhOnK9WJjDObyqUePxFJEzSB39mBWxX5pvPE/iYdiCKUqEvi4DEIc4yVQjC8k23VUBVWotP21CEQL0e9UENWTRXWNvpvJC6r0jPpcAUskyhy5xPPjGelGHnCDYNKm3unKBgb8ja7dWPCqUbQZPciZWBxUeD2yrq37Mn0EdcrX6OShkcP4XLTRmy24Asl8dh0bGKzSJ0IlMMFTHot8BiWmUKvL+aR1WQrCPigPTHYLjW22gwbHe3zNepYgVsA7SQ5EMVmvEl30oy+tj4YMAkbm8WOOXYCbWQjqHr+b27IhNmzsIdhDNORu5gx6lFhhrKJoe3Mg2oy923/cLz3bjqQI++8oE48aVsnQT1RTrT0KEQ6lCdwqZ2w2KbnZtjUs3zhFJ2IaChPAw6CfGdlYviosop0vcGyb5dAJWZCOouU4="
          on:
            tags: true
#    - stage: docs
#      script: yarn docs:prepare && yarn docs:build
#      node_js: "8"
#      deploy:
#        provider: pages
#        local-dir: hygen.io/public
#        skip-cleanup: true
#        github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#        keep-history: true
#    - stage: binary releases
#      script: yarn standalone
#      if: tag =~ ^v\d.*
#      node_js: "8"
#      deploy:
#        provider: releases
#        api_key: $GITHUB_TOKEN
#        file_glob: true
#        file: standalone/*
#        skip_cleanup: true
#        on:
#          tags: true
